# Generated by Django 5.2.1 on 2025-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=350)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField()),
                ('delai', models.DateTimeField()),
                ('participation', models.IntegerField()),
                ('participants', models.ManyToManyField(to='auth_app.scoutuser')),
            ],
        ),
    ]
