# Generated by Django 5.1.5 on 2025-05-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('event_app', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FORMATION', 'Formation'), ('AG', 'Assemblée Générale'), ('JAMBOREE', 'Jamborée'), ('RENTREE_SCOUTE', 'Rentrée scoute')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='auth_app.scoutuser'),
        ),
    ]
